name: Update Anime Tracker

on:
  workflow_dispatch:

  schedule:
    # Anime-Sama : toutes les 30 minutes
    - cron: "17,47 5-20 * * *"
      timezone: "Europe/Paris"

    # MAL : une fois par jour
    - cron: "7 5 * * *"
      timezone: "Europe/Paris"

concurrency:
  group: anime-update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      SHEET_ID: 1WuGg-AH0X1x5ZdOswZlwn5KxE-V0TKeYTxovN20E9UE
      SHEET_NAME: Anime
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.AnimeTrackerSecretAccountJsonGoogleService }}
      MAL_CLIENT_ID: ${{ secrets.MAL_CLIENT_ID }}

      RUN_MAL: ${{ github.event_name == 'workflow_dispatch' || github.event.schedule == '7 5 * * *' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run updater
        run: node scripts/update-anime.mjs
